/*
 * Copyright 2026 Quaternion8192
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package cc.quaternion.potshaper;

import java.util.concurrent.atomic.AtomicInteger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Manages the allocation and validation of unique identifiers (UUIDs) for PotShaper.
 *
 * <p>This class generates sequential UUIDs with a specific prefix and format.
 * It also provides static utility methods to parse and validate UUID strings
 * generated by this manager. UUIDs follow the pattern "POT:" followed by an
 * 8-character uppercase hexadecimal number, representing a monotonically
 * increasing integer value.</p>
 *
 * <h3>UUID Format</h3>
 * <pre>POT:XXXXXXXX</pre>
 * Where XXXXXXXX is an 8-digit uppercase hexadecimal number.
 *
 * @author Quaternion8192
 * @since 1.0
 */
class UuidManager {

    /** The constant prefix for all UUIDs generated by this manager. */
    private static final String UUID_PREFIX = "POT:";

    /** The pattern used to validate UUID strings. */
    private static final Pattern UUID_PATTERN = Pattern.compile("POT:([0-9A-Fa-f]{8})");

    /** The internal counter used to generate unique sequential integer values. */
    private final AtomicInteger counter;

    /**
     * Constructs a new UUID manager starting the allocation sequence from zero.
     *
     * <p>The first allocated UUID will have the hexadecimal value "00000001".</p>
     */
    UuidManager() {
        this.counter = new AtomicInteger(0);
    }

    /**
     * Allocates and returns a new unique identifier.
     *
     * <p>This method atomically increments an internal counter and formats the
     * resulting integer as an 8-digit uppercase hexadecimal string, prefixed
     * with "POT:". The sequence starts from 1.</p>
     *
     * <h3>Usage Example</h3>
     * <pre>{@code
     * UuidManager manager = new UuidManager();
     * String id1 = manager.allocate(); // Returns "POT:00000001"
     * String id2 = manager.allocate(); // Returns "POT:00000002"
     * }</pre>
     *
     * @return a new UUID string following the format "POT:XXXXXXXX".
     */
    String allocate() {
        int value = counter.incrementAndGet();
        return UUID_PREFIX + String.format("%08X", value);
    }

    /**
     * Parses a UUID string and extracts its underlying integer value.
     *
     * <p>This method validates the input string against the expected UUID pattern.
     * If the string matches, it extracts the hexadecimal portion and converts it
     * to an integer. If the string is null, does not match the pattern, or contains
     * an invalid hexadecimal number, the method returns -1.</p>
     *
     * <h3>Usage Example</h3>
     * <pre>{@code
     * int val1 = UuidManager.parseUuidValue("POT:0000000A"); // Returns 10
     * int val2 = UuidManager.parseUuidValue("POT:INVALID");  // Returns -1
     * int val3 = UuidManager.parseUuidValue(null);           // Returns -1
     * }</pre>
     *
     * @param uuid the UUID string to parse, may be null.
     * @return the integer value represented by the UUID, or -1 if the UUID is
     *         null, malformed, or contains an invalid hexadecimal number.
     */
    static int parseUuidValue(String uuid) {
        if (uuid == null) {
            return -1;
        }
        Matcher matcher = UUID_PATTERN.matcher(uuid);
        if (matcher.matches()) {
            try {
                return Integer.parseInt(matcher.group(1), 16);
            } catch (NumberFormatException e) {
                return -1;
            }
        }
        return -1;
    }

    /**
     * Checks if a given string is a valid UUID generated by this manager.
     *
     * <p>A valid UUID must be non-null and exactly match the pattern
     * "POT:" followed by 8 hexadecimal digits (case-insensitive).</p>
     *
     * <h3>Usage Example</h3>
     * <pre>{@code
     * boolean b1 = UuidManager.isValidUuid("POT:00AB12FF"); // Returns true
     * boolean b2 = UuidManager.isValidUuid("pot:00ab12ff"); // Returns true
     * boolean b3 = UuidManager.isValidUuid("POT:123");      // Returns false
     * boolean b4 = UuidManager.isValidUuid(null);           // Returns false
     * }</pre>
     *
     * @param uuid the string to validate, may be null.
     * @return {@code true} if the string is a valid UUID, {@code false} otherwise.
     */
    static boolean isValidUuid(String uuid) {
        return uuid != null && UUID_PATTERN.matcher(uuid).matches();
    }
}